name: assistantflutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependency_overrides:
#冲突的版本兼容
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: 5.0.0
  #  吐司
  flutter_easyloading: ^2.2.2
  # 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.0
  #加密
  crypto: ^3.0.1
  common_utils: ^2.0.2
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  sp_util: ^2.0.3
  #下拉刷新
  pull_to_refresh: ^2.0.0
  #路由管理
  fluro: ^2.0.3
  json_annotation: ^3.0.1
  #tab的指示器
  bubble_tab_indicator: ^0.1.6
  fading_edge_scrollview: ^2.0.0
  flutter_screenutil: ^3.2.0
  cached_network_image: ^3.0.0
  path_provider: ^2.0.2
  smooth_star_rating: ^1.1.1
  #轮播图
  flutter_card_swipper: ^0.4.0
  #富文本
  flutter_html: ^2.0.0
  #webview
  webview_flutter: ^2.0.8
  #图片查看器
  photo_view: ^0.11.1
  #网络连接检查
  connectivity: ^3.0.3
  sensors: ^2.0.3

  #  cupertino_icons: ^1.0.2
#  #  吐司
#  flutter_easyloading: ^3.0.5
#  # 网络库 https://github.com/flutterchina/dio
#  dio: ^4.0.0
#  sp_util: ^2.0.3
#  provider: ^6.0.0
#
#  #下拉刷新
#  pull_to_refresh: ^2.0.0
#  #路由管理
#  fluro: ^2.0.3
#  #tab的指示器
#  bubble_tab_indicator: ^0.1.6
#  fading_edge_scrollview: ^2.0.0
#  #富文本
#  flutter_html: ^2.2.1
#
#  #轮播图
#  flutter_card_swipper: ^0.4.0
#  #图片查看器
#  photo_view: ^0.11.1
#  archive: ^3.1.2
#  cryptoutils: ^0.5.0
#  path_provider: ^2.0.2
#  #视频播放器
#  video_player: ^2.1.6
#  #唤醒
#  url_launcher: ^6.0.0
#
#  #json 库
#  json_annotation: ^4.4.0
#  common_utils: ^2.1.0






  # 生成Dart代码文件
  # 配合使用命令：flutter packages pub run build_runner build
  # 配合使用命令：flutter packages pub run build_runner watch
  # flutter packages pub run build_runner build --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
#  flutter_lints: ^1.0.4
#  build_runner: ^2.0.0
#  json_serializable: ^6.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/jin10/
    - assets/images/


  module:
    androidX: true
    androidPackage: com.example.assistantflutter
    iosBundleIdentifier: com.example.assistantflutter
